import { ref } from 'vue'
import type { VideoMetadata } from '../types/media'

export const selectedTags = ref<string[]>([])
export const playMode = ref<'shuffle' | 'shuffle-tags' | 'search'>('shuffle')
export const queuedVideos = ref<VideoMetadata[]>([])
export const selectedVideo = ref<VideoMetadata | null>(null)
export const nextShuffleVideo = ref<VideoMetadata | null>(null)
export const shuffleHistory = ref<VideoMetadata[]>([])
export const selectedGirls = ref<string[]>([])
export const onlyNoThemes = ref(false)
export const onlyNoGirls = ref(false)
export const tagMatchMode = ref<'any' | 'all'>('any')
export const girlMatchMode = ref<'any' | 'all'>('any')
export const videosInDatabase = ref<VideoMetadata[]>([])
export const lastWeightedPick = ref<VideoMetadata | null>(null)
export const lastWeightedCandidates = ref<VideoMetadata[]>([])
export const suppressHistoryOnce = ref(false)
export const lastPickProbability = ref<number | null>(null)
export const videoSrc = ref<string>('')
export const videoEl = ref<HTMLVideoElement | null>(null)
export const currentTime = ref(0)
export const duration = ref(0)
export const videoWidth = ref(0)
export const videoHeight = ref(0)
export const isPlaying = ref(false)
export const volume = ref(1)
export const isMuted = ref(false)
export const audioContext = ref<AudioContext | null>(null)
export const pendingDelete = ref('no')
export const pendingEditOptions = ref<string[]>([])
export const pendingUpdateFormOptions = ref<string[]>([])
export const pendingUpdateGirls = ref('')
export const pendingUpdateThemes = ref('')
export const volumeBeforeMute = ref(1)
